services:
  postgres:
    image: postgres:16.1-alpine
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: D1K2u61s06C8jnCM
      POSTGRES_DB: vaultapwerup
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
